# Nombre del servicio
spring.application.name=registration-service

# Puerto (diferente a todos los demás)
server.port=8086

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_registration_service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA - Hibernate crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# URLs de otros servicios
tournament.service.url=http://localhost:8085
user.service.url=http://localhost:8082
sanction.service.url=http://localhost:8090
team.service.url=http://localhost:8084